name: Close Issues with Specific Labels
on:
  issues:
    types: [labeled]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if labeled completed or wontfix
        run: |
          if [[ " ${{ toJson(github.event.issue.labels.*.name) }} " =~ " completed " ]] || [[ " ${{ toJson(github.event.issue.labels.*.name) }} " =~ " wontfix " ]]; then
            curl -X PATCH https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"state":"closed"}'
          fi
